version: '3.8'

services:
  api:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "6000:8000"
    volumes:
      - .:/app
      - ./app.log:/app/app.log
    env_file:
      - .env
    restart: unless-stopped 