version: "3.3"

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "6000:6000"
    volumes:
      - .:/app
      - ./app.log:/app/app.log
      - ./generated_htmls:/app/generated_htmls
      - ./generated_pdfs:/app/generated_pdfs
    env_file:
      - .env
    restart: unless-stopped
